config/routes.rb
Rails.application.routes.draw do

  resources :departamentos
  root "produtos#index"

  resources :usuarios

  #get "produtos" => "produtos#index"
  #get "produtos/hello" => "produtos#hello"
  #get "/produtos/new" => "produtos#new"
  #delete "/produtos/:id" => "produtos#destroy", as: :produto
  #post "/produtos" => "produtos#create"
  resources :produtos, only: [:new, :create, :destroy, :edit, :update]
  get "/produtos/busca" => "produtos#busca", as: :busca_produto

  get "usuarios" => "usuarios#index"

end

app/models/departamento.rb
class Departamento < ActiveRecord::Base
end

app/models/perfil.rb
class Perfil < ActiveRecord::Base
  validates_presence_of :role, :nome, :status
  validates :descricao, presence: true
end

app/models/produto.rb
class Produto < ActiveRecord::Base

    belongs_to :departamento 

    validates :quantidade, presence: true
    validates :nome, length: {minimum: 5}
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  validates_presence_of :dsc_senha, :dsc_login
  validates_confirmation_of  :dsc_senha
  validates_length_of :dsc_login, minimum: 8, allow_blank: false
  validates_length_of :dsc_login, in: 5..10
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/departamentos_controller.rb
class DepartamentosController < ApplicationController
  before_action :set_departamento, only: [:show, :edit, :update, :destroy]

  # GET /departamentos
  def index
    @departamentos = Departamento.all
  end

  # GET /departamentos/1
  def show
  end

  # GET /departamentos/new
  def new
    @departamento = Departamento.new
  end

  # GET /departamentos/1/edit
  def edit
  end

  # POST /departamentos
  def create
    @departamento = Departamento.new(departamento_params)

    if @departamento.save
      redirect_to @departamento, notice: 'Departamento was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /departamentos/1
  def update
    if @departamento.update(departamento_params)
      redirect_to @departamento, notice: 'Departamento was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /departamentos/1
  def destroy
    @departamento.destroy
    redirect_to departamentos_url, notice: 'Departamento was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_departamento
      @departamento = Departamento.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def departamento_params
      params.require(:departamento).permit(:nome)
    end
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController

  before_action :set_produto, only: [:edit, :update, :destroy]

  def hello
    @message = "Marcelo Bento Ferreira"
  end

  def index
    @produtos = Produto.all.order(descricao: :desc).limit(20)
  end

  def busca
      @nome_a_buscar = params[:nome]
      @produtos_buscado = Produto.where "nome like ?", "%#{@nome_a_buscar}%"

  end

  def edit
    renderiza_edit
  end

  def update
    if @produto.update produto_params
      flash[:notice] = "Registro atualizado com sucesso"
      redirect_to root_url
    else
      render :edit
    end
  end



  def new
          @produto = Produto.new
          @departamentos = Departamento.all
  end

  def create
    @produto = Produto.new produto_params
    if @produto.save
        flash[:notice] = "Criado com sucesso!"
        redirect_to root_url
    else
        render :new
    end

  end

  def destroy
    @produto.destroy
    redirect_to root_url
  end

  private

  def set_produto
    id = params[:id]
    @produto = Produto.find(id)
  end

  def renderiza_new
    @departamentos = Departamento.all
    render :new
  end

  def renderiza_edit
    @departamentos = Departamento.all
    renderiza :edit
  end

  def renderiza(view)
    render view
  end

  def produto_params
    params.require(:produto).permit(:nome, :preco, :descricao, :quantidade, :departamento_id)
  end

end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :set_usuario, only: [:show, :edit, :update, :destroy]

  # GET /usuarios
  def index
    @usuarios = Usuario.all
  end

  # GET /usuarios/1
  def show
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
  end

  # GET /usuarios/1/edit
  def edit
  end

  # POST /usuarios
  def create
    @usuario = Usuario.new(usuario_params)

    if @usuario.save
      redirect_to @usuario, notice: 'Usuario was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /usuarios/1
  def update
    if @usuario.update(usuario_params)
      redirect_to @usuario, notice: 'Usuario was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /usuarios/1
  def destroy
    @usuario.destroy
    redirect_to usuarios_url, notice: 'Usuario was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def usuario_params
      params.require(:usuario).permit(:isn_usuario, :dsc_login, :dsc_senha)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departamentos_helper.rb
module DepartamentosHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/departamentos/_form.html.erb
<%= form_for(@departamento) do |f| %>
  <% if @departamento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@departamento.errors.count, "error") %> prohibited this departamento from being saved:</h2>

      <ul>
      <% @departamento.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/departamentos/edit.html.erb
<h1>Editing Departamento</h1>

<%= render 'form' %>

<%= link_to 'Show', @departamento %> |
<%= link_to 'Back', departamentos_path %>

app/views/departamentos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Departamentos</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @departamentos.each do |departamento| %>
      <tr>
        <td><%= departamento.nome %></td>
        <td><%= link_to 'Show', departamento %></td>
        <td><%= link_to 'Edit', edit_departamento_path(departamento) %></td>
        <td><%= link_to 'Destroy', departamento, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Departamento', new_departamento_path %>

app/views/departamentos/new.html.erb
<h1>New Departamento</h1>

<%= render 'form' %>

<%= link_to 'Back', departamentos_path %>

app/views/departamentos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @departamento.nome %>
</p>

<%= link_to 'Edit', edit_departamento_path(@departamento) %> |
<%= link_to 'Back', departamentos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Loja de Camisetas</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= nav_bar brand: "Loja", brand_link: root_url do %>
      <%= form_tag busca_produto_path, method: :get, class: "navbar-form navbar-right" do %>
          <div class="form-group" >
              <%= text_field_tag :nome, @nome_a_buscar, class: "form-control" %>
              <%= button_to "Buscar", nil, class:"btn btn-default" %>
          </div>
      <% end %>
  <% end %>

  <div class="container">

      <%= yield %>

  </div>

</body>
</html>

app/views/produtos/_form.html.erb
<% @produto.errors.full_messages.each do |message| %>
    <div class="alert alert-danger">
        <%= message %>
    </div>
<% end %>

  <%= form_for @produto do |f| %>

  <div class="form-group">
    <%= f.label :nome%>
    <%= f.text_field :nome, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :descricao%>
    <%= f.text_area :descricao, class: "form-control", rows:4 %>
  </div>

  <div class="form-group">
    <%= f.label :departamento %>
    <%= f.collection_select :departamento_id, @departamentos, :id, :nome , {}, class:"form-control" %>
  </div>

  <div class="form-inline">
    <%= f.label :quantidade%>
    <%= f.number_field :quantidade, step:1, class: "form-control"%>

    <%= f.label :preco%>
    <%= f.number_field :preco, class: "form-control" %>
  </div>

    <%= f.submit texto_da_acao, class:"btn btn-primary"%>

  <% end %>

app/views/produtos/_produto.html.erb
<tr>
  <th><%= produto.nome %></th>
  <th><%= produto.descricao %></th>
  <th><%= produto.quantidade %></th>
  <th><%= produto.preco %></th>
  <th><%= button_to "Remover", produto , method: :delete, class:"btn btn-danger", data:{confirm:"Deseja realmente remover #{produto.nome} ?"} %></th>
  <th><%= link_to "Alterar", edit_produto_path(produto), class:"btn btn-success" %></th>
</tr>

app/views/produtos/busca.html.erb
    <h1><%= @message %></h1>
    <table class="table table-bordered">
        <thead>
          <tr>
            <th>Nome</th>
            <th>Descrição</th>
            <th>Preço</th>
            <th>Quantidade</th>
            <th>Ação</th>
        </tr>
        </thead>
        <tbody>
          <%= render partial: "produto", collection: @produtos_buscado %>
        </tbody>
    </table>

    <%= link_to "Criar", new_produto_path %>

app/views/produtos/edit.html.erb
<%= render partial: 'form', locals: {texto_da_acao: 'Atualizar'} %>

app/views/produtos/hello.html.erb
<h1>A Greeting for You!</h1>
<p><%= @message %></p>

app/views/produtos/index.html.erb
<% if flash[:notice] %>
  <div class="alert alert-info" role="alert"><%= flash[:notice] %></div>
<% end %>
    <h1><%= @message %></h1>
    <table class="table table-bordered">
        <thead>
          <tr>
            <th>Nome</th>
            <th>Descrição</th>
            <th>Preço</th>
            <th>Quantidade</th>
            <th>Excluir</th>
            <th>Editar</th>
        </tr>
        </thead>
        <tbody>
          <%= render @produtos  %>
        </tbody>
    </table>

    <%= link_to "Criar", new_produto_path %>

app/views/produtos/new.html.erb
<%= render partial: 'form', locals: {texto_da_acao: 'Criar'} %>

app/views/usuarios/_form.html.erb
<%= form_for(@usuario) do |f| %>
  <% if @usuario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>

      <ul>
      <% @usuario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :isn_usuario %><br>
    <%= f.text_field :isn_usuario %>
  </div>
  <div class="field">
    <%= f.label :dsc_login %><br>
    <%= f.text_field :dsc_login %>
  </div>
  <div class="field">
    <%= f.label :dsc_senha %><br>
    <%= f.text_field :dsc_senha %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/usuarios/edit.html.erb
<h1>Editing Usuario</h1>

<%= render 'form' %>

<%= link_to 'Show', @usuario %> |
<%= link_to 'Back', usuarios_path %>

app/views/usuarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Usuarios</h1>

<table>
  <thead>
    <tr>
      <th>Isn usuario</th>
      <th>Dsc login</th>
      <th>Dsc senha</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @usuarios.each do |usuario| %>
      <tr>
        <td><%= usuario.isn_usuario %></td>
        <td><%= usuario.dsc_login %></td>
        <td><%= usuario.dsc_senha %></td>
        <td><%= link_to 'Show', usuario %></td>
        <td><%= link_to 'Edit', edit_usuario_path(usuario) %></td>
        <td><%= link_to 'Destroy', usuario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Usuario', new_usuario_path %>

app/views/usuarios/new.html.erb
<h1>New Usuario</h1>

<%= render 'form' %>

<%= link_to 'Back', usuarios_path %>

app/views/usuarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Isn usuario:</strong>
  <%= @usuario.isn_usuario %>
</p>

<p>
  <strong>Dsc login:</strong>
  <%= @usuario.dsc_login %>
</p>

<p>
  <strong>Dsc senha:</strong>
  <%= @usuario.dsc_senha %>
</p>

<%= link_to 'Edit', edit_usuario_path(@usuario) %> |
<%= link_to 'Back', usuarios_path %>